# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- script: |
#    wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb && sudo dpkg -i pandoc-2.7.3-1-amd64.deb
#    sudo apt-get update && sudo apt-get install texlive-full inkscape pandoc-citeproc
#  displayName: 'Install Dependencies'
#
#- script:  make pdf_cicd
#  displayName: 'build thesis'

- task: 'retrieve secrets'
  inputs:
    azureSubscription: 'Microsoft Azure Enterprise (80710935-9dd3-4f6f-a587-8c84723a457c)'
    KeyVaultName: 's18344-keys'
    SecretsFilter: '*'
- script: echo $(owncloud-pw)