version: '3.0'

services:
  thesisbldr:
    image: shogoki/thesisbuilder
    environment:
      - owncloud-pw=${owncloud-pw}
      - owncloud-password=${owncloud-pw}
    volumes:
      - .:/usr/src/app